### ISSUE TITLE
Compilation against Geant 4.11.1.0 fails

### ISSUE THREAD

**Issue by olifre** [vmc-project/vgm#10]
Likely to be expected, but: Compilation fails, since `packages/Geant4GM/include/Geant4GM/solids/MultiUnion.h` assumes `G4Types.hh`  (for definitition of `G4int`) is indirectly included via `G4Transform3D.hh`. 
Geant 4.11.1 has cleaned up their headers a bit, so `G4Types.hh` needs to be included directly. 

After patching this, `VGM` tests don't compile since `g4root` seems to link against `Geant4::G4gl2ps` which is now gone from Geant 4.

**Comment by ihrivnac** [comment]
Thank you for reporting the issue, the update and new tag based on Geant4 11.1 is now in preparation.  Besides the fix of the compilation error, there is also slightly updated CMake. If you are volunteering to test on your side the update, I can notify you, when master is updated.

On the other hand, I do not get any problem with `Geant4::G4gl2ps`; there are no explicit Geant4 library dependencies in `g4root` defined. Did you try to build VGM with G4Root built against older Geant4 ?
As`Geant4 VMC` needs also an update to compile with Geant4 11.1, I plan to synchronise first both master branches, and then tag both VGM and Geant4 VMC.

**Comment by ihrivnac** [comment]
@olifre , the master branch is now updated with all changes.

**Comment by olifre** [comment]
Sorry for the delay — and thanks for the quick updates! I can likely only give it a try after Christmas, but I can already respond to one question now:

> On the other hand, I do not get any problem with `Geant4::G4gl2ps`; there are no explicit Geant4 library dependencies in `g4root` defined. Did you try to build VGM with G4Root built against older Geant4 ?

I realize what happened here: I did update Geant4, but I did not recompile `geant4_vmc` afterwards. Hence, `geant4_vmc` kept the dependency on `Geant4::G4gl2ps` in the generated CMake definitions, which in turn were picked up by VGM when compiling tests / examples. 

This also means there's a bug in my packaging for Gentoo Linux: For every update of Geant4, also `geant4_vmc` needs to be rebuilt. I'll fix that in the next version bump :-). 

I'll ping you again once I've been able to test latest master(s). Thanks again for the quick response!

**Comment by olifre** [comment]
@ihrivnac I ran the full series of test suites for both `geant4_vmc` master and `vgm` master, and also tested our framework afterwards using the new version of the stack. No issues, it worked like a charm, so I can confirm compatibility with Geant 4.11.1.0 :-). 
Many thanks again! Feel free to close the issue (or leave it open until the next release of VGM, as you prefer).

**Comment by ihrivnac** [comment]
@olifre , thank you for testing. The tag 5.1 is now available; the tag in geant4_vmc will follow.
